### ISSUE TITLE
Unable to load a tile

### ISSUE THREAD

**Issue by binay567** [Microsoft/PowerBI-CSharp#15]
I am unable to load the Power BI dashboard tiles in my web application but I am able to load the reports. I am getting infinite spinning at  the time of loading a tile although i have implemented onload function in iframe which sends the following data to API.
 action: "loadTile", accessToken: accessToken

**Comment by wbreza** [comment]
Are you using Power BI Embedded on Azure or our standard user based offering at powerbi.com?

**Comment by wbreza** [comment]
Let us know if you are still experencing this issue.

**Comment by segheysens** [comment]
Hi Wallace, I'm experiencing this issue. I'm pulling the tile from a dashboard hosted on my PowerBI Pro account - does it need to be served fromPowerBI Embedded on Azure?

**Comment by wbreza** [comment]
Hi @segheysens.  No, you do not need to serve the tile from Power BI Embedded on Azure.  Have a look at the sample [here](https://github.com/Microsoft/PowerBI-CSharp/tree/master/samples/webforms/embed-a-tile-into-an-app) which will walk you through setting up your tile embed.

If you continue to have issues please capture a fiddler trace and I will be able to investigate further.

**Comment by segheysens** [comment]
Hi Wallace, can I email you a copy of my trace, due to client privacy concerns? The embed request is visible in the report that I captured. I followed that tutorial, and my access token, iframe source URL, and message structure look fine. I'd be happy to share each of these with you over email or Skype (Microsoft and New Signature are federated, so you can message me at sgheysens@newsignature or email me at the same).

**Comment by wbreza** [comment]
Yes - feel free to email me. wabreza@microsoft.com
