### ISSUE TITLE
Safely storing JWTs of AccessToken and RefreshToken

### ISSUE THREAD

**Issue by IshamMohamed** [Microsoft/PowerBI-CSharp#26]
I am developing a Windows Forms application to show Power BI reports. Where my intention is to get the AccessToken for a user, store it and refresh it so user does not have to login again and again to Power BI via my application even if they close the application. 
I am currently encrypting the AccessToken and write it in a text file. My question is, Is this legal? if not what is the appropriate way to do this.

**Comment by wbreza** [comment]
Sounds like you are using Azure AD authentication with PowerBI?  If this is the case you can generate both access tokens and refresh tokens using Azure AD OAuth.  Ensure that you are generating and storing your refresh token in a backend server.  The refresh token should never be exposed otherwise it could be used to generate new access tokens without the users consent.

**Comment by IshamMohamed** [comment]
Is it legal to encrypt them and store them in user machine?

**Comment by wbreza** [comment]
I cannot provide legal advice, but technically speaking if you are encrypting them and taking the necessary precautions to keep the key private you should be OK.
